### ISSUE TITLE
有没有QQ群之类的，准备拿你这个架子学学react

### ISSUE THREAD

**Issue by wangyupo** [yjd-cli/react-ts-project-template#1]
我也有一个和你目的类似的架子，不过是vue的，地址在[这里](https://github.com/wangyupo/vue-vuex-router)，你这个更适合入门React的新手，我也想学学你的这个，咱俩可以交流交流。

**Comment by wangyupo** [comment]
我也有一个类似目的的架子，是vue的，地址在这里：https://github.com/wangyupo/vue-vuex-router，不过我感觉你这个更好，对于新入门react的同学来说可能会更友好，咱俩可以交流交流

**Comment by yjdjiayou** [comment]
yaojiadong945 可以加我微信交流
